* Pho 

This is an instruction to cook 5 liters (about 5.5 quarts) of Pho. 

For about 4 people to feel pretty full.

** Prerequisites

*** Ingredients

**** Spices

- Black cardamom: 1 seed
- Cloves: 3-5 buds
- Fennel seeds: 1 gram
- Coriander seeds: 1.5 grams
- Star anises: 2 stars
- White peppercorns: 20 peppercorns
- Cinnamon stick: 1 stick

**** Vegetables

- Onions: 3 medium
- Shallots: 3 small
- Gingers: 2 big
- Lemons: 2
- Limes: 4-6

**** Meats

- Chuck Roast (Angus Beef): 1 kg
- Shaved  Steak (Angus Beef): 500 gram
- Meatball (Angus Beef): 20 balls
- Quail eggs: optional

Note: Preferred Angus Beef for extra flavor

**** Others

- Rice noodle (Erawan brands - M size)
- Marrow Bones: 1-2 kg (Preferred thigh bones)

*** Equipments

- 10-12 quarts stockpot with glass lid
    - Brand: Cuisinart or Calphalon or T-fal
    - Purpose: Soup broth

- 5-6 quarts stockpot with glass lid
    - Brand: Cuisinart or Calphalon or T-fal
    - Purpose: Slow cook beef chuck

- Micro-perforated Stainless Steel 5-quart Colander
    - Brand: Bellemain
    - Purpose: Rice Noodle strainer

*** Steps

**** Clean marrow bones

- Wash the bones with cold water couple times

- Chop a medium ginger

- Cut a lemon in quarters

- Make a big bowl of cold water, chopped ginger, squeezed lemon juice and sea salt

- Put the bones in that bowl for 1 hour

**** Process spices

- Fry spices on medium heat until the fragrant released

- Soak and rinse the spices in the warm water 30 minutes to reduce the dark/burnt color and reduce the strong taste (cinnamon, cardamom, cloves)

- Put all spices in a cotton spice bag

- Make 2 bags (1 for stock pot, 1 for meat pot)

- Put a bag in the soup pot and one in the meat pot

Note: If a spice bag is dipped for too long, it will cause the darken color and strong smell. Only dip for 1 hour and refigerator for later use.

**** Slow-cook chuck in meat pot

- Cut the chuck into big pieces (the pieces will get smaller after a long cook time. Estimate and make it a good bite size)

- Put above meat, ginger, onion, shallot and a spice bag in a 5 quarts stock bag

- Add water to cover all the meat

- Add a lot of salt, fish sauce, alcohol (whiskey, spiced rum or mei kwei lu), pepper

- Put on medium-high heat and make sure the water is hot enough that it is bubbled. Don't make it overboiled

- Cook for about 4 hours.

Note: If beef is cooked for more than 4 hours, there will be sourness taste.
One way to overcome this is soak beef or pre-cook it in hot water once.

**** Cut vegetables

- Cut onion into thin slices like paper then dip it in cold water to reduce pungent taste

- Cut limes into wedges

**** Cook stock pot

- 
